// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixkzggoirpiairtvrqxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4a3pnZ29pcnBpYWlydHZycXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjAzMzQsImV4cCI6MjA2NzEzNjMzNH0.tc9L42zv51wxI5UlTyEgUijrz53nswiDZqxvRz5Ay3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});